# Generated by Django 5.0.3 on 2024-04-16 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_orderitem_product'),
        ('product', '0013_alter_category_options_alter_category_name'),
        ('store', '0004_profile_old_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='product.product'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_farmer',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
