# Generated by Django 5.0.3 on 2024-04-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_created_at_product_lifespan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='Listed_Date',
        ),
    ]
