# Generated by Django 5.0.3 on 2024-04-10 04:49

import django.db.models.deletion
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_category_category_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=product.models.default_category_id, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
