# Generated by Django 5.0.3 on 2024-04-10 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
    ]
