# Generated by Django 5.0.3 on 2024-03-30 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='products_imgs/')),
                ('slug', models.CharField(max_length=400)),
                ('detail', models.TextField()),
                ('specs', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.category')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.farmer')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.size')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.type')),
            ],
        ),
    ]
